import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container-fluid">
          <div className="row pt-5 pb-3">
            <div className="col-4 offset-1 d-flex flex-column justify-content-center align-items-start">
              <h1 className="fs-1 fw-normal mb-5">SUPER AUTHENTIC</h1>
              <p className="fs-4 mb-5">
                
Our expert team in designer brands can verify the authenticity of new & pre-owned luxury goods. Just within 12-24 hours after uploading your pictures, you’ll receive an authentication result.

              </p>
              <a className="button">Get Start</a>
            </div>
            <div className="col-7 py-5">
              <div className="cover">

              </div>
            </div>
          </div>

        </div>
      </main>
    </div>
  )
}
